---
title: "Pandemic Pass? Treaty Derogations and Human Rights Practices During COVID-19"
author:
- name: Suparna Chaudhry
  affiliation: Lewis and Clark College
  orcid: 0000-0003-3506-7590
  url: https://www.suparnachaudhry.com/
  email: schaudhry@lclark.edu
- name: Audrey L. Comstock
  affiliation: Arizona State University
  orcid: 0000-0003-1772-5350
  url: https://audreylcomstock.weebly.com/
  email: audrey.comstock@asu.edu
- name: Andrew Heiss
  affiliation: Georgia State University
  orcid: 0000-0002-3948-3914
  url: https://www.andrewheiss.com
  email: aheiss@gsu.edu
format:
  html:
    code-tools: false
sidebar: false
---

In an effort to combat the COVID-19 pandemic, many countries declared states of emergency and derogated (temporarily suspended) from their international human rights treaty obligations. Did states actually end up complying with their pandemic-era derogations? Did derogating and non-derogating states implement emergency measures differently, and if so, how? Using data from the Varieties of Democracy PanDem dataset and the Oxford Covid-19 Government Response Tracker, we find that states which derogated from their international human rights obligations imposed emergency measures that were temporary and non-discriminatory. On the other hand, states that did not derogate were more likely impose discriminatory measures, enact emergency measures without time limits and violate non-derogable rights. Our results support the role that flexibility mechanisms such as derogations play in international law.
