project:
  type: website

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "Pandemic Pass"
  search: false
  navbar:
    background: primary
    pinned: true
    right:
      - icon: github
        aria-label: github
        href: https://github.com/andrewheiss/mountainous-mackerel
  sidebar:
    style: docked
    background: dark
    contents:
      - section: Data and workflow
        contents:
          - data-final.qmd
          - data-details.qmd
          - targets.qmd
      - section: Hypotheses
        contents:
          - hypotheses.qmd
      - section: Analysis
        contents:
          - analysis_h1.qmd
          - analysis_h2.qmd
          - analysis_h3.qmd

format:
  html:
    theme: 
      - litera
      - html/custom.scss
    toc: true
    toc-depth: 4
    highlight-style: monokai
    code-fold: true
    code-tools: true
